### ISSUE TITLE
Error message when using Heroku button

### ISSUE THREAD

**Issue by jjb** [ur0/statusify#21] opened 2015-10-09 19:09 UTC
> No app.json located in the repo URL provided.
>
> Make sure that an app.json file exists in the project root directory.

**Comment by ur0** [comment] 2015-10-09 19:31
Hi @jjb

This issue is the same as #18 and was fixed in 4b08b8b. I've just checked, the issue isn't there. However, if you still face this, feel free to reopen this issue.

**Closed by ur0** 2015-10-09 19:31 UTC
